### ISSUE TITLE
fees are divided twice by precisionfactor

### ISSUE THREAD

**Issue by Luivatra** [PhoenixErgo/phoenix-hodlcoin-contracts#1]
The fees seem to be hit by a precisionfactor twice

https://github.com/PhoenixErgo/phoenix-hodlcoin-contracts/blob/4c2ec5afac6115f723c845e937eeef5065fc1540/contracts/bank_contract/v1/ergoscript/phoenix_v1_hodlcoin_bank.es#L152C9-L152C9

**Comment by ldgaetano** [comment]
This is from the original contract. The precision factor gets cancelled out.
`val price: Long = (reserveIn * precisionFactor) / hodlCoinsCircIn`
`val expectedAmountDeposited: Long = (hodlCoinsCircDelta * price) / precisionFactor`
`val expectedAmountBeforeFees: Long = (hodlCoinsBurned * price) / precisionFactor`

**Comment by Luivatra** [comment]
yes but the fees get divided by precisionfactor again:
```
val bankFeeAmount: Long = (expectedAmountBeforeFees * bankFee._1) / (bankFee._2 * precisionFactor)
val devFeeAmount: Long = (expectedAmountBeforeFees * devFee._1) / (devFee._2 * precisionFactor)
```

**Comment by ldgaetano** [comment]
Ah yes that is wrong it seems 👍

**Comment by ldgaetano** [comment]
I fixed it to this:

```
val bankFeeAmount: Long = (expectedAmountBeforeFees * bankFee._1) / bankFee._2
val devFeeAmount: Long = (expectedAmountBeforeFees * devFee._1) / devFee._2
```

commit: https://github.com/PhoenixErgo/phoenix-hodlcoin-contracts/commit/64826da59bad1f899f63b874e8faf02a4e4491c1
