### ISSUE TITLE
Bank Withdraw Amount Issue

### ISSUE THREAD

**Issue by mgpai22** [PhoenixErgo/phoenix-hodlcoin-contracts#10]
https://github.com/PhoenixErgo/phoenix-hodlcoin-contracts/blob/0dcd47f75e2507d15071d7da5707fa87b69d32a4/contracts/bank_contract/v1/ergoscript/phoenix_v1_hodlcoin_bank.es#L134

The above line is incorrect 

it should be either
```
val validBankWithdraw: Boolean = (reserveOut == reserveIn - expectedUserAmount - devFeeAmount)
```
or 
```
val validBankWithdraw: Boolean = (reserveOut == reserveIn - expectedAmountBeforeFees + bankFeeAmount)
```
I like the latter because its more intuitive. The bank looses amount due to fees + fee it keeps.

Kushti implemented the former in the [offchain testing code](https://github.com/PhoenixErgo/phoenix/blob/106680cde07eeb80038f92d708af78dcc0d2b0eb/src/test/scala/mockchain/PhoenixSpec.scala#L322) but I think that can be a bit confusing.

**Comment by ldgaetano** [comment]
@mgpai22 Yes implement the last option and make pr.
